spring.application.name=progreso2-integracion-salud360

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Apache Camel
camel.springboot.name=Salud360IntegrationApp
camel.springboot.main-run-controller=true

# Server
server.port=8080

# Logging
logging.level.edu.udla.integracion=DEBUG
logging.level.org.apache.camel=INFO
